import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface GateAnalysisData {
  documentType: string;
  reliability?: string;
  executiveSummary: {
    verdict: string;
    score: number;
    topRisks?: string[];
    topCorrections?: string[];
    tokenizationLevel?: string;
    comment?: string;
  };
  scores?: {
    infrastructure: number;
    production: number;
    financials: number;
    risks: number;
  };
  keyFindings?: {
    infrastructure?: string;
    production?: string;
    financials?: string;
    dependencies?: string;
  };
  metrics?: {
    epr?: string;
    ebitda?: string;
    capexQuality?: string;
  };
  redFlags?: string[];
  fullAnalysis?: string;
  tippingFeeSummary?: {
    detected: boolean;
    transparency?: string;
    is_assumption?: boolean;
    tf_net_low?: number;
    tf_net_base?: number;
    tf_net_high?: number;
    tf_share?: number;
    contract_confidence?: string;
    contract_tenor_years?: number;
    customer_concentration_pct?: number;
  };
  baseCaseComparison?: {
    with_tipping: {
      revenue: number;
      ebitda: number;
      ebitda_margin_pct: number;
    };
    without_tipping: {
      revenue: number;
      ebitda: number;
      ebitda_margin_pct: number;
    };
  };
  tippingScoring?: {
    penalties_applied: string[];
    total_penalty_points: number;
    auto_reject_triggered: boolean;
  };
}

export function exportGateReportToPDF(data: GateAnalysisData) {
  const doc = new jsPDF();
  
  // Check if auto-reject was triggered
  const autoReject = data.tippingScoring?.auto_reject_triggered || false;
  
  // === HEADER ===
  // Leviathan Gate logo background - RED if auto-rejected, INDIGO otherwise
  if (autoReject) {
    doc.setFillColor(220, 38, 38); // red-600
  } else {
    doc.setFillColor(79, 70, 229); // indigo-600
  }
  doc.rect(0, 0, 210, 40, 'F');
  
  // Title
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('Leviathan Gate', 14, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Where capital decides, not narratives.', 14, 25);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  if (autoReject) {
    doc.text('⛔ REJECTED BY LEVIATHAN GATE', 14, 34);
  } else {
    doc.text('Project Viability Report', 14, 34);
  }
  
  // Generated by
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 255);
  doc.text('Generated by Leviathan OS', 150, 34);
  
  let yPos = 50;
  
  // === EXECUTIVE SUMMARY ===
  doc.setFillColor(243, 244, 246); // gray-100
  doc.rect(14, yPos - 5, 182, 50, 'F');
  
  doc.setFontSize(16);
  doc.setTextColor(31, 41, 55); // gray-800
  doc.setFont('helvetica', 'bold');
  doc.text('Resumen Ejecutivo', 18, yPos + 3);
  
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128); // gray-500
  doc.setFont('helvetica', 'normal');
  doc.text(`Tipo de Documento: ${data.documentType || 'N/A'}`, 18, yPos + 11);
  
  // Score - Large and prominent
  doc.setFontSize(36);
  const scoreColor = getScoreColor(data.executiveSummary.score);
  doc.setTextColor(scoreColor.r, scoreColor.g, scoreColor.b);
  doc.setFont('helvetica', 'bold');
  doc.text(`${data.executiveSummary.score}`, 170, yPos + 15);
  
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.setFont('helvetica', 'normal');
  doc.text('SCORE', 172, yPos + 21);
  
  // Gate Decision
  doc.setFontSize(12);
  doc.setTextColor(31, 41, 55);
  doc.setFont('helvetica', 'bold');
  doc.text('Gate Decision:', 18, yPos + 21);
  
  const gateVerdict = getGateVerdict(data.executiveSummary.score);
  doc.setFontSize(11);
  doc.setTextColor(scoreColor.r, scoreColor.g, scoreColor.b);
  doc.setFont('helvetica', 'bold');
  doc.text(gateVerdict, 18, yPos + 28);
  
  // Original Verdict
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  doc.setFont('helvetica', 'normal');
  doc.text(`Veredicto Original: ${data.executiveSummary.verdict || 'N/A'}`, 18, yPos + 36);
  
  yPos += 55;
  
  // === SCORES BREAKDOWN ===
  doc.setFontSize(14);
  doc.setTextColor(31, 41, 55);
  doc.setFont('helvetica', 'bold');
  doc.text('Desglose de Puntuación', 14, yPos);
  
  yPos += 10;
  
  if (data.scores) {
    const scoresData = [
      ['Categoría', 'Puntos', 'Máximo'],
      ['Infraestructura', `${data.scores.infrastructure}`, '30'],
      ['Producción', `${data.scores.production}`, '25'],
      ['Finanzas', `${data.scores.financials}`, '25'],
      ['Riesgos', `${data.scores.risks}`, '20'],
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [scoresData[0]],
      body: scoresData.slice(1),
      theme: 'grid',
      headStyles: {
        fillColor: [79, 70, 229], // indigo-600
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10,
      },
      bodyStyles: {
        fontSize: 9,
      },
      columnStyles: {
        0: { cellWidth: 80 },
        1: { cellWidth: 50, halign: 'center' },
        2: { cellWidth: 50, halign: 'center' },
      },
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  // === TOP RISKS ===
  if (data.executiveSummary.topRisks && data.executiveSummary.topRisks.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(220, 38, 38); // red-600
    doc.setFont('helvetica', 'bold');
    doc.text('⚠ Top 5 Riesgos Identificados', 14, yPos);
    
    yPos += 8;
    
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    
    data.executiveSummary.topRisks.forEach((risk, index) => {
      const splitRisk = doc.splitTextToSize(`${index + 1}. ${risk}`, 180);
      doc.text(splitRisk, 18, yPos);
      yPos += splitRisk.length * 5;
    });
    
    yPos += 5;
  }
  
  // === TOP CORRECTIONS ===
  if (data.executiveSummary.topCorrections && data.executiveSummary.topCorrections.length > 0) {
    // Check if we need a new page
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235); // blue-600
    doc.setFont('helvetica', 'bold');
    doc.text('✓ Top 5 Correcciones Necesarias', 14, yPos);
    
    yPos += 8;
    
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    
    data.executiveSummary.topCorrections.forEach((correction, index) => {
      const splitCorrection = doc.splitTextToSize(`${index + 1}. ${correction}`, 180);
      doc.text(splitCorrection, 18, yPos);
      yPos += splitCorrection.length * 5;
    });
    
    yPos += 5;
  }
  
  // === TOKENIZATION LEVEL ===
  if (data.executiveSummary.tokenizationLevel) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(147, 51, 234); // purple-600
    doc.setFont('helvetica', 'bold');
    doc.text('Nivel de Tokenización', 14, yPos);
    
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    doc.text(data.executiveSummary.tokenizationLevel, 18, yPos);
    
    yPos += 10;
  }
  
  // === KEY FINDINGS (New Page) ===
  if (data.keyFindings) {
    doc.addPage();
    yPos = 20;
    
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55);
    doc.setFont('helvetica', 'bold');
    doc.text('Hallazgos Clave', 14, yPos);
    
    yPos += 10;
    
    if (data.keyFindings.infrastructure) {
      doc.setFontSize(12);
      doc.setTextColor(37, 99, 235);
      doc.setFont('helvetica', 'bold');
      doc.text('Infraestructura y Maquinaria', 14, yPos);
      
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setTextColor(75, 85, 99);
      doc.setFont('helvetica', 'normal');
      const infraText = doc.splitTextToSize(data.keyFindings.infrastructure, 180);
      doc.text(infraText, 14, yPos);
      yPos += infraText.length * 4 + 8;
    }
    
    if (data.keyFindings.production) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(12);
      doc.setTextColor(22, 163, 74); // green-600
      doc.setFont('helvetica', 'bold');
      doc.text('Producción', 14, yPos);
      
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setTextColor(75, 85, 99);
      doc.setFont('helvetica', 'normal');
      const prodText = doc.splitTextToSize(data.keyFindings.production, 180);
      doc.text(prodText, 14, yPos);
      yPos += prodText.length * 4 + 8;
    }
    
    if (data.keyFindings.financials) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(12);
      doc.setTextColor(147, 51, 234); // purple-600
      doc.setFont('helvetica', 'bold');
      doc.text('Finanzas', 14, yPos);
      
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setTextColor(75, 85, 99);
      doc.setFont('helvetica', 'normal');
      const finText = doc.splitTextToSize(data.keyFindings.financials, 180);
      doc.text(finText, 14, yPos);
      yPos += finText.length * 4 + 8;
    }
  }
  
  // === TIPPING FEE SUMMARY ===
  if (data.tippingFeeSummary && data.tippingFeeSummary.detected) {
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(16);
    doc.setTextColor(79, 70, 229); // indigo-600
    doc.setFont('helvetica', 'bold');
    doc.text('Tipping Fee Summary', 14, yPos);
    
    yPos += 10;
    
    // Summary card
    doc.setFillColor(238, 242, 255); // indigo-50
    doc.rect(14, yPos, 182, 55, 'F');
    
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    
    doc.text(`Transparency: ${data.tippingFeeSummary.transparency || 'N/A'}`, 18, yPos + 8);
    doc.text(`TF Share: ${data.tippingFeeSummary.tf_share?.toFixed(1) || 'N/A'}% of revenue`, 18, yPos + 16);
    
    // Add ASSUMPTION indicator if values are not explicitly stated
    const assumptionLabel = data.tippingFeeSummary.is_assumption ? ' (ASSUMPTION)' : '';
    doc.text(`TF Net LOW: $${data.tippingFeeSummary.tf_net_low?.toLocaleString() || 'N/A'}/ton${assumptionLabel}`, 18, yPos + 28);
    doc.text(`TF Net BASE: $${data.tippingFeeSummary.tf_net_base?.toLocaleString() || 'N/A'}/ton${assumptionLabel}`, 70, yPos + 28);
    doc.text(`TF Net HIGH: $${data.tippingFeeSummary.tf_net_high?.toLocaleString() || 'N/A'}/ton${assumptionLabel}`, 122, yPos + 28);
    
    doc.text(`Contract Confidence: ${data.tippingFeeSummary.contract_confidence || 'N/A'}`, 18, yPos + 38);
    doc.text(`Tenor: ${data.tippingFeeSummary.contract_tenor_years || 'N/A'} years`, 100, yPos + 38);
    doc.text(`Customer Concentration: ${data.tippingFeeSummary.customer_concentration_pct?.toFixed(0) || 'N/A'}%`, 18, yPos + 46);
    
    yPos += 65;
  }
  
  // === BASE CASE COMPARISON ===
  if (data.baseCaseComparison) {
    if (yPos > 210) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(16);
    doc.setTextColor(147, 51, 234); // purple-600
    doc.setFont('helvetica', 'bold');
    doc.text('Base Case vs With-Tipping Comparison', 14, yPos);
    
    yPos += 10;
    
    // Comparison table
    doc.setFillColor(250, 245, 255); // purple-50
    doc.rect(14, yPos, 182, 50, 'F');
    
    doc.setFontSize(11);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'bold');
    doc.text('Con Tipping Fee', 18, yPos + 8);
    doc.text('Sin Tipping Fee (Base Case)', 110, yPos + 8);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    // With Tipping
    doc.text(`Revenue: $${data.baseCaseComparison.with_tipping.revenue.toLocaleString()}`, 18, yPos + 18);
    doc.text(`EBITDA: $${data.baseCaseComparison.with_tipping.ebitda.toLocaleString()}`, 18, yPos + 26);
    const withMarginColor = data.baseCaseComparison.with_tipping.ebitda_margin_pct >= 12 ? [22, 163, 74] : [220, 38, 38];
    doc.setTextColor(withMarginColor[0], withMarginColor[1], withMarginColor[2]);
    doc.setFont('helvetica', 'bold');
    doc.text(`EBITDA Margin: ${data.baseCaseComparison.with_tipping.ebitda_margin_pct.toFixed(1)}%`, 18, yPos + 34);
    
    // Without Tipping
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    doc.text(`Revenue: $${data.baseCaseComparison.without_tipping.revenue.toLocaleString()}`, 110, yPos + 18);
    doc.text(`EBITDA: $${data.baseCaseComparison.without_tipping.ebitda.toLocaleString()}`, 110, yPos + 26);
    const withoutMarginColor = data.baseCaseComparison.without_tipping.ebitda_margin_pct >= 12 ? [22, 163, 74] : [220, 38, 38];
    doc.setTextColor(withoutMarginColor[0], withoutMarginColor[1], withoutMarginColor[2]);
    doc.setFont('helvetica', 'bold');
    doc.text(`EBITDA Margin: ${data.baseCaseComparison.without_tipping.ebitda_margin_pct.toFixed(1)}%`, 110, yPos + 34);
    
    // Warning if base case < 12%
    if (data.baseCaseComparison.without_tipping.ebitda_margin_pct < 12) {
      yPos += 44;
      doc.setFillColor(254, 242, 242); // red-50
      doc.rect(14, yPos, 182, 10, 'F');
      doc.setFontSize(9);
      doc.setTextColor(220, 38, 38); // red-600
      doc.setFont('helvetica', 'bold');
      doc.text('⚠️ EBITDA base case inferior al 12% - Proyecto no viable sin tipping fee contratado', 18, yPos + 6);
      yPos += 10;
    } else {
      yPos += 50;
    }
    
    yPos += 10;
  }
  
  // === TIPPING SCORING IMPACT ===
  if (data.tippingScoring) {
    if (yPos > 210) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(16);
    doc.setTextColor(245, 158, 11); // amber-500
    doc.setFont('helvetica', 'bold');
    doc.text('Tipping Scoring Impact', 14, yPos);
    
    yPos += 10;
    
    // Scoring impact card
    doc.setFillColor(255, 251, 235); // amber-50
    doc.rect(14, yPos, 182, 25, 'F');
    
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Penalty Points: -${data.tippingScoring.total_penalty_points}`, 18, yPos + 8);
    
    const rejectColor = data.tippingScoring.auto_reject_triggered ? [220, 38, 38] : [22, 163, 74];
    doc.setTextColor(rejectColor[0], rejectColor[1], rejectColor[2]);
    doc.setFont('helvetica', 'bold');
    doc.text(`Auto Reject Triggered: ${data.tippingScoring.auto_reject_triggered ? 'YES' : 'NO'}`, 18, yPos + 16);
    
    yPos += 30;
    
    // Penalties applied list
    if (data.tippingScoring.penalties_applied && data.tippingScoring.penalties_applied.length > 0) {
      doc.setFontSize(11);
      doc.setTextColor(75, 85, 99);
      doc.setFont('helvetica', 'bold');
      doc.text('Penalizaciones Aplicadas:', 14, yPos);
      
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      data.tippingScoring.penalties_applied.forEach((penalty) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        const penaltyText = doc.splitTextToSize(`• ${penalty}`, 180);
        doc.text(penaltyText, 18, yPos);
        yPos += penaltyText.length * 5;
      });
      
      yPos += 5;
    }
    
    // Auto reject warning
    if (data.tippingScoring.auto_reject_triggered) {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFillColor(254, 242, 242); // red-50
      doc.rect(14, yPos, 182, 10, 'F');
      doc.setFontSize(9);
      doc.setTextColor(220, 38, 38);
      doc.setFont('helvetica', 'bold');
      doc.text('🚨 AUTO REJECT: Proyecto no viable sin tipping fee contratado y EBITDA base < 12%', 18, yPos + 6);
      yPos += 15;
    }
  }
  
  // === FOOTER (All pages) ===
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175); // gray-400
    doc.text('Leviathan Gate — Project Viability Report', 14, 285);
    doc.text('Generated by Leviathan OS', 14, 290);
    doc.text(`Página ${i} de ${pageCount}`, 180, 290, { align: 'right' });
  }
  
  // Save PDF
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`Leviathan-Gate-Report-${timestamp}.pdf`);
}

function getScoreColor(score: number): { r: number; g: number; b: number } {
  if (score >= 85) return { r: 22, g: 163, b: 74 }; // green-600
  if (score >= 70) return { r: 37, g: 99, b: 235 }; // blue-600
  if (score >= 50) return { r: 245, g: 158, b: 11 }; // amber-500
  return { r: 220, g: 38, b: 38 }; // red-600
}

function getGateVerdict(score: number): string {
  if (score >= 70) return 'Passed the Gate';
  if (score >= 50) return 'Conditional Gate Approval';
  return 'Rejected by the Gate';
}
